### ISSUE TITLE
Add Alpha value to `scrollbarSlider`

### ISSUE THREAD

**Issue by DarkStoorM** [thomasabishop/alien-blood-vscode#1]
The color for scrollbar slider needs an alpha value, because git line changes and other line highlights are invisible

The current state:
![img](https://user-images.githubusercontent.com/7021295/148375115-e4df2d9f-d687-4186-a313-a34b50389bbd.png)

With color alpha value:
![img](https://user-images.githubusercontent.com/7021295/148375314-cd0d1355-3a7d-4306-8c44-f2ee98a1db37.png)

I used the following settings:

```json
"scrollbarSlider.background": "#112616bb",
"scrollbarSlider.hoverBackground": "#1d4125bb",
```

You could also make use of the missing `activeBackground` property

```json
"scrollbarSlider.activeBackground": "#266134bb",
```

This will override the colors when scrolling
![img](https://user-images.githubusercontent.com/7021295/148375774-fe0c29c2-9ebf-4d8d-8784-bc18b3a557ed.png)

These are just example colors, they need some adjustment 😄 

Before and After:

![diff](https://user-images.githubusercontent.com/7021295/148376609-948dc835-e7e0-4d49-9d2f-13f62dd943ab.png)

**Comment by thomasabishop** [comment]
Hey thanks for the feedback. I will take a look soon and implement your suggestions.

**Comment by thomasabishop** [comment]
This issue has now been resolved. Please let me know if you have any feedback. If you enjoy the theme it would be wonderful if you could rate it on the marketplace, thank you.
